apiVersion: apps/v1
kind: Deployment
metadata:
  name: registerapp-deployment
  labels:
    app: register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: register-app
        image: ashfaque9x/java-registration-app:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080